- src/electionguard-ui/ElectionGuard.UI.sln
Fixes #172 
The UI test project seems to be mostly checking that Maui is doing Maui things. Remove.
> Remove UI test project

- Makefile
Fixes #190
Makefile issues when copying to new folder. Updated to build and copy.
> fix darwin input for netstandard tests

- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/CiphertextBallot.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/NativeInterface.cs
- include/electionguard/ballot.h
- include/electionguard/ballot.hpp
- src/electionguard/ballot.cpp
- src/electionguard/facades/ballot.cpp
Fixes #201 
Add C++ and c# code to handle having an extra state to the ballots and that will be the challenged state.
> Add new ballot state

- .gitignore
- src/electionguard-db/mongo-init.js
- src/electionguard-ui/ElectionGuard.UI.Lib/Services/Database/BallotService.cs
- src/electionguard-ui/ElectionGuard.UI.Lib/Services/Database/BallotUploadService.cs
- src/electionguard-ui/ElectionGuard.UI.Lib/Services/Database/CiphertextTallyService.cs
- src/electionguard-ui/ElectionGuard.UI.Lib/Services/Database/ConstantsService.cs
- src/electionguard-ui/ElectionGuard.UI.Lib/Services/Database/ContextService.cs
- src/electionguard-ui/ElectionGuard.UI.Lib/Services/Database/DbService.cs
- src/electionguard-ui/ElectionGuard.UI.Lib/Services/Database/GuardianBackupService.cs
- src/electionguard-ui/ElectionGuard.UI.Lib/Services/Database/GuardianPublicKeyService.cs
- src/electionguard-ui/ElectionGuard.UI.Lib/Services/Database/LagrangeCoefficientsService.cs
- src/electionguard-ui/ElectionGuard.UI.Lib/Services/Database/PlaintextSpoiledBallotService.cs
- src/electionguard-ui/ElectionGuard.UI.Lib/Services/Database/PlaintextTallyService.cs
- src/electionguard-ui/ElectionGuard.UI.Lib/Services/Database/TallyService.cs
- src/electionguard-ui/ElectionGuard.UI.Lib/Services/Database/VerificationService.cs
fixed the ballot service
Fixes #229
Added indexes to the mongodb initialization
> cleanup the mono indexes

- src/electionguard-ui/ElectionGuard.UI.Lib/Models/TallyJoinedRecord.cs
- src/electionguard-ui/ElectionGuard.UI.Lib/Services/Database/TallyJoinedService.cs
- src/electionguard-ui/ElectionGuard.UI/Resx/AppResources.Designer.cs
- src/electionguard-ui/ElectionGuard.UI/Resx/AppResources.es.resx
- src/electionguard-ui/ElectionGuard.UI/Resx/AppResources.resx
- src/electionguard-ui/ElectionGuard.UI/ViewModels/TallyProcessViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/Views/TallyProcessPage.xaml
Fixes some of #185
Allow Guardians to assert consent in joining a tally
> Join tally

- src/electionguard-ui/ElectionGuard.UI.sln
- src/electionguard-ui/ElectionGuard.UI/ElectionGuard.UI.csproj
> Add Decryption to UI

- bindings/netstandard/ElectionGuard/ElectionGuard.Decryption.Tests/Decryption/TestDecryptWithShares.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Decryption/Challenge/BallotChallenge.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Decryption/Challenge/CreateChallenge.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Decryption/ChallengeResponse/CreateChallengeResponse.cs
do not dispose ballots between tests. add missing assignment
Decryption tests were failing due to a swapped assignment.
> swap string assignment

- src/electionguard-ui/ElectionGuard.UI/Views/TallyProcessPage.xaml
Fixes #___
Fixed some xaml for the display
> cleanup of the ui

- src/electionguard/manifest.cpp
- test/electionguard/generators/manifest.hpp
- test/electionguard/test_ballot.c
- test/electionguard/test_election.c
- test/electionguard/test_encrypt.c
> Handle contest description with title and no subtitle

- bindings/netstandard/ElectionGuard/ElectionGuard.Decryption.Tests/Decryption/DecryptionMediatorExtensions.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Decryption.Tests/Decryption/TestDecryptWithShares.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Decryption/Shares/CreateShares.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Decryption/Shares/DecryptionShare.cs
Fixes #271 
Added an interface for passing in the decryption share without ballots. This should provide the necessary interface support for decryptign without challenge ballots.
> Enable executing a tally without challenge ballots

- bindings/netstandard/ElectionGuard/ElectionGuard.Decryption/Shares/DecryptionShare.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/Base/DisposableBase.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/Candidate.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/ElectionGuardException.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/NativeInterface.cs
- src/electionguard-ui/ElectionGuard.UI.Lib/Models/ContestItem.cs
- src/electionguard-ui/ElectionGuard.UI.Lib/Models/TallyRecord.cs
- src/electionguard-ui/ElectionGuard.UI.Lib/Services/Database/BallotService.cs
- src/electionguard-ui/ElectionGuard.UI.Lib/Services/Interfaces/IDatabaseService.cs
- src/electionguard-ui/ElectionGuard.UI/Controls/ContestControl.xaml
- src/electionguard-ui/ElectionGuard.UI/Controls/ContestControl.xaml.cs
- src/electionguard-ui/ElectionGuard.UI/Helpers/ElectionRecordGenerator.cs
- src/electionguard-ui/ElectionGuard.UI/Resx/AppResources.Designer.cs
- src/electionguard-ui/ElectionGuard.UI/Resx/AppResources.es.resx
- src/electionguard-ui/ElectionGuard.UI/Resx/AppResources.resx
- src/electionguard-ui/ElectionGuard.UI/ViewModels/AdminHomeViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/CreateTallyViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/GuardianHomeViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/ManifestViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/ViewTallyViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/Views/TallyProcessPage.xaml
- src/electionguard-ui/ElectionGuard.UI/Views/ViewTallyPage.xaml
Fixes #185
Fixes #290 
Display the results of the tally on the tally view page.  
Fix the scrolling of the page
Create an election
upload encrypted ballots
Perform a tally
View the tally
> Update the view tally display to show the results of the tally

- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/ElectionGuardException.cs
- src/electionguard-ui/ElectionGuard.UI.Lib/Extensions/ObservableCollectionExtension.cs
- src/electionguard-ui/ElectionGuard.UI.Lib/Models/TallyStatesEnum.cs
- src/electionguard-ui/ElectionGuard.UI.Lib/Services/Database/TallyJoinedService.cs
- src/electionguard-ui/ElectionGuard.UI.Lib/Services/Database/TallyService.cs
- src/electionguard-ui/ElectionGuard.UI/Helpers/TallyCanBeAbandonedConverter.cs
- src/electionguard-ui/ElectionGuard.UI/Helpers/TallyNotStartedConverter.cs
- src/electionguard-ui/ElectionGuard.UI/Models/GuardianTallyItem.cs
- src/electionguard-ui/ElectionGuard.UI/Models/TallyCeremonyChecklist.cs
- src/electionguard-ui/ElectionGuard.UI/Resx/AppResources.Designer.cs
- src/electionguard-ui/ElectionGuard.UI/Resx/AppResources.es.resx
- src/electionguard-ui/ElectionGuard.UI/Resx/AppResources.resx
- src/electionguard-ui/ElectionGuard.UI/Services/TallyStateMachine.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/ElectionViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/TallyProcessViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/Views/TallyProcessPage.xaml
Fixes #291
Update tally processing based on feedback in June 1 and June 2 demo
> Tally processing updates

- src/electionguard-ui/ElectionGuard.UI/ViewModels/BallotUploadViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/ElectionViewModel.cs
Fixes #301
Fixes #259
Update election after upload. Makes `ElectionViewModel` take different query params
> Update election after upload

- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption.Bench/BenchManifest.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption.Tests/TestManifest.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption.Utils/Generators/ManifestGenerator.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/Manifest.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/NativeInterface.cs
- include/electionguard/manifest.h
- include/electionguard/manifest.hpp
- src/electionguard/facades/manifest.cpp
- src/electionguard/manifest.cpp
- src/electionguard/serialize.hpp
- test/electionguard/generators/manifest.hpp
- test/electionguard/test_manifest.c
- test/electionguard/test_manifest.cpp
Fixes #269 
Adds spec_version to manifest import and export as a required value
> add specversion to manifest

- src/electionguard-ui/ElectionGuard.UI/Views/CreateElectionAdminPage.xaml
- src/electionguard-ui/ElectionGuard.UI/Views/CreateElectionAdminPage.xaml.cs
Fixes #300
Worked around the display issue for font color
> Added fix for key ceremony picker.

- bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/StateMachineStep.cs
- src/electionguard-ui/ElectionGuard.UI/Services/TallyStateMachine.cs
Fixes #303
Update the tally state machine to support multiple tallies. This eliminates some potential 🚗 conditions and upgrades the mutex.
Run a tally.
> Support multiple tallies - state machine

- .github/workflows/release.yml
> fix binary assignment

- Makefile
- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption.Tests/ElectionGuard.Encryption.Tests.csproj
- src/electionguard-ui/ElectionGuard.UI/Converters/TallyCanBeAbandonedConverter.cs
- src/electionguard-ui/ElectionGuard.UI/Converters/TallyCompleteConverter.cs
- src/electionguard-ui/ElectionGuard.UI/Converters/TallyNotStartedConverter.cs
- src/electionguard-ui/ElectionGuard.UI/Converters/TallyStateConverter.cs
- src/electionguard-ui/ElectionGuard.UI/Models/TallyCeremonyChecklist.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/TallyProcessViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/Views/TallyProcessPage.xaml
Fixes #297 
UI updates for tally processing
> Additional Tally Updates

- scripts/fixMauiPublishImages.ps1
- src/electionguard-ui/ElectionGuard.UI/ElectionGuard.UI.csproj
Fixes #325 
Adds the rasterized generated images that maui produces to the publish folder using a script associated with the following github issue. Thanks to the op for making this available.
https://github.com/dotnet/maui/issues/10526
> copy image files to publish folder

- .github/workflows/release.yml
- Makefile
Fixes #331 
Fail publish step if the secrets are not set
> fail when no secret is available

- src/electionguard-ui/ElectionGuard.UI/ViewModels/GuardianHomeViewModel.cs
Fix renaming issue for guardian home page
> Fix renaming issue

- src/electionguard-ui/ElectionGuard.UI.Lib/Models/MultiTallyRecord.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/TallyProcessViewModel.cs
> Fix tuple build issues

- .github/workflows/pull-request-ui.yml
- .github/workflows/pull-request.yml
> try fix CI filters

- src/electionguard-ui/ElectionGuard.UI.Test/ViewModels/AdminHomeViewModelTest.cs
- src/electionguard-ui/ElectionGuard.UI.Test/ViewModels/CreateKeyCeremonyAdminViewModelTest.cs
> fix ui tests

- .github/workflows/pull-request.yml
> do not check for source in equality comparison

- bindings/netstandard/ElectionGuard/ElectionGuard.Decryption.Tests/ElectionGuard.Decryption.Tests.csproj
- bindings/netstandard/ElectionGuard/ElectionGuard.Decryption/ElectionGuard.Decryption.csproj
- bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup.Tests/ElectionGuard.ElectionSetup.Tests.csproj
- bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/ElectionGuard.ElectionSetup.csproj
- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption.Utils/ElectionGuard.Encryption.Utils.csproj
- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/ElectionGuard.Encryption.csproj
- src/electionguard-ui/Directory.Packages.props
> Bump UI encryption library to use 1.75.16

- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/ElectionGuard.Encryption.csproj
- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/Electionguard.Encryption.targets
- libs/hacl/CMakeLists.txt
> fix hacl dll resolution

- bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/Guardian/GuardianStorageExtensions.cs
- src/electionguard-ui/ElectionGuard.UI/Models/TallyCeremonyChecklist.cs
- src/electionguard-ui/ElectionGuard.UI/Resources/Styles/EgStyles.xaml
- src/electionguard-ui/ElectionGuard.UI/Resx/AppResources.Designer.cs
- src/electionguard-ui/ElectionGuard.UI/Resx/AppResources.es.resx
- src/electionguard-ui/ElectionGuard.UI/Resx/AppResources.resx
- src/electionguard-ui/ElectionGuard.UI/Services/ITallyStateMachine.cs
- src/electionguard-ui/ElectionGuard.UI/Services/TallyManager.cs
- src/electionguard-ui/ElectionGuard.UI/Services/TallyStateMachine.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/BaseViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/GuardianHomeViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/LoginViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/TallyProcessViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/ViewKeyCeremonyViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/Views/LoginPage.xaml
- src/electionguard-ui/ElectionGuard.UI/Views/LoginPage.xaml.cs
- src/electionguard-ui/ElectionGuard.UI/Views/TallyProcessPage.xaml
> various ui cleanups.

- src/electionguard-ui/Directory.Packages.props
- src/electionguard-ui/ElectionGuard.UI/ElectionGuard.UI.csproj
- src/electionguard-ui/ElectionGuard.UI/MauiProgram.cs
- src/electionguard-ui/ElectionGuard.UI/Services/ConfigurationService.cs
- src/electionguard/serialize.hpp
Fixes #___
Changed version number of UI
Changed version number of manifest generation
Added AppCenter Analytics
> ev testing changes

- src/electionguard-ui/ElectionGuard.UI/ViewModels/CreateTallyViewModel.cs
> Crash resolve - create tally without dates

- src/electionguard-ui/ElectionGuard.UI/ElectionGuard.UI.csproj
- src/electionguard-ui/ElectionGuard.UI/ViewModels/CreateTallyViewModel.cs
Fixes #381
In some cases, a timing issue occurred where the list update is rendered before the list actually has the data. This creates a situation where the index is out of range.
> Fix create tally crash

- src/electionguard-ui/ElectionGuard.UI/ViewModels/ElectionViewModel.cs
> Only ready drives need to be reviewed

- bindings/netstandard/ElectionGuard/ElectionGuard.Decryption/Decryption/CiphertextDecryptionTally.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Decryption/DecryptionMediator.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/BallotUploadViewModel.cs
> Enhance tally logging

- Makefile
- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption.Tests/TestManifest.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption.Utils/Generators/ManifestGenerator.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/ElectionType.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/Manifest.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/PrecomputeBufferContext.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/ReportingUnitType.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/VoteVariationType.cs
Fixed issues related to integration testing with election equipment manifacturer.
> Changes due to integration testing with election product

- apps/electionguard-cli/Generate/GenerateCommand.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Decryption/Decryption/CiphertextDecryptionTally.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Decryption/Tally/PlaintextTally.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/AdminHomeViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/BallotUploadViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/BaseViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/CreateElectionViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/ElectionViewModel.cs
Closes #407 
Closes #408 
Closes #409
Closes #396 
Closes #402 
> QA updates from integration test with CP Vendor

- src/electionguard-ui/ElectionGuard.UI/Resources/Styles/EgStyles.xaml
> Fixed mismatched style

- src/electionguard-ui/Directory.Packages.props
- src/electionguard-ui/ElectionGuard.UI.Lib/Services/FileSystem/ZipService.cs
- src/electionguard-ui/ElectionGuard.UI/ElectionGuard.UI.csproj
Update App version
Fix linting warning.
Fixes #___
Updated UI version for release
Updated to new community toolkit for various fixes
Fixed linter warning on _zipfile
> Update CommunityToolkit version

- src/electionguard-ui/ElectionGuard.UI/Platforms/Windows/Package.appxmanifest
- src/electionguard-ui/ElectionGuard.UI/ViewModels/AdminHomeViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/Views/AdminHomePage.xaml
> #415 - Force data to show by marshalling to the UI thread

- src/electionguard-ui/ElectionGuard.UI/ElectionGuard.UI.csproj
- src/electionguard-ui/ElectionGuard.UI/Platforms/Windows/Package.appxmanifest
- src/electionguard-ui/ElectionGuard.UI/ViewModels/BallotUploadViewModel.cs
Fixes #437
One of our vendors needs `artifacts/devices` folder to auto import.
> Support multiple device folders

- src/electionguard-ui/ElectionGuard.UI/ElectionGuard.UI.csproj
- src/electionguard-ui/ElectionGuard.UI/Platforms/Windows/Package.appxmanifest
- src/electionguard-ui/ElectionGuard.UI/ViewModels/BaseViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/CreateKeyCeremonyAdminViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/ViewKeyCeremonyViewModel.cs
- src/electionguard-ui/ElectionGuard.UI/ViewModels/ViewTallyViewModel.cs
Fixes #452
Fixes #453
Fixed issue with creating key ceremony
Fixed issue with guardian username being blank.
Added logging for the tally viewing
Upped version number
manually test with vendor Manifest
Tested all the way to tally export
> Fix issue for creating key ceremony and joining them.

- src/electionguard-ui/ElectionGuard.UI/Controls/ContestControl.xaml
- src/electionguard-ui/ElectionGuard.UI/ElectionGuard.UI.csproj
- src/electionguard-ui/ElectionGuard.UI/Platforms/Windows/Package.appxmanifest
- src/electionguard-ui/ElectionGuard.UI/ViewModels/BallotUploadViewModel.cs
Fixed 2 memory leaks around ballot uploading.
Updated version to 13.
Resolves Tally display issue for vendor
> Removed the totals and percentages from being displayed.

- bindings/netstandard/ElectionGuard/ElectionGuard.Decryption.Tests/Challenge/TestChallenge.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Decryption/Verify/VerifyElection.cs
Add clarification to the use of M and T when recomputing hashes for Verification 9
> Add clarification for test and verification of T and M

- .github/workflows/release.yml
- bindings/netstandard/ElectionGuard/ElectionGuard.Decryption/Challenge/BallotChallenge.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Decryption/Challenge/SelectionChallenge.cs
- bindings/netstandard/ElectionGuard/ElectionGuard.Decryption/Challenge/TallyChallenge.cs
- src/electionguard-ui/ElectionGuard.UI/ElectionGuard.UI.csproj
- src/electionguard-ui/ElectionGuard.UI/Platforms/Windows/Package.appxmanifest
- src/electionguard-ui/ElectionGuard.UI/Services/TallyManager.cs
Fixes #476 
The verification system showed that the Challege value that is serialized out is not what was expected.  This is because the value is getting multiplied by the coefficient again.  This means that it is not what is expected by anyone making a verifier.
Run an election and a tally.  Export the election Record, use a verifier on the election record.
> Verification fix

- Makefile
Fixes #483 
Change the publishing step to use the new appcenter account.
> Switched to new appcenter

- Makefile
Fixes #490 
Moved the publishing to new AppCenter account.
> Move appcenter to publish from new account
